import type { Metadata } from "next";
import { Libre_Franklin, JetBrains_Mono, Caveat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./provider";

const libre_Franklin = Libre_Franklin({ 
  subsets: ["latin"],
  weight: "400",
  variable: "--font-libre-franklin",
});

const jetBrains_Mono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: "--font-jetbrains-mono" 
});

const caveat = Caveat({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: "--font-caveat" 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${libre_Franklin.variable} ${jetBrains_Mono.variable} ${caveat.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
